### ISSUE TITLE
Codestyle issue NoCommentFixer.php

### ISSUE THREAD

**Issue by PiotrFedak** [blumilksoftware/codestyle#126] opened 2024-06-19 10:31 UTC
Error code

`PHP Fatal error:  Class Blumilk\Codestyle\Fixers\NoCommentFixer contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (PhpCsFixer\Fixer\ConfigurableFixerInterface::configure) in /home/runner/work/blt/blt/vendor/blumilksoftware/codestyle/src/Fixers/NoCommentFixer.php on line 19
Script ./vendor/bin/php-cs-fixer fix --dry-run --diff --config codestyle.php handling the cs event returned with error code 255
Error: Process completed with exit code 255.
`

**Comment by JakubKermes** [comment] 2024-06-19 12:06
```php
final class NoCommentFixer extends AbstractFixer implements ConfigurableFixerInterface
{
    public function getConfigurationDefinition(): FixerConfigurationResolver
    {
        return new FixerConfigurationResolver([
            (new FixerOptionBuilder("doc_comment", "Docblock comments should be removed."))
                ->setAllowedTypes(["bool"])
                ->setDefault(false)
                ->getOption(),
        ]);
    }
    public function configure(array $configuration):void
    {
    }
``` 
this seems to resolve problem, but we can also limit version of cs fixer to 3.59.2
```php
    "friendsofphp/php-cs-fixer": "v3.59.2",
``` 
from 3.59.3, which also works

**Comment by krzysztofrewak** [comment] 2024-06-19 14:37
Duplicate of #124.

**Closed** 2024-06-19 14:37 UTC
Labels: bug

**Comment by mtracz** [comment] 2024-06-20 08:17
@JakubKermes 
New release `v3.2.1` should works now.

**Comment by PiotrFedak** [comment] 2024-06-20 08:22
@mtracz  yes, works fine after new release, thanks
